package cmd

import (
	"github.com/urfave/cli"
	"github.com/zhuharev/tamework"
)

var (
	// CmdBot for command usage
	CmdBot = cli.Command{
		Name:   "bot",
		Action: runBot,
	}
)

func runBot(ctx *cli.Context) {
	tw, err := tamework.New("434621599:AAGS-yyWLsDQ1LJeUs4yULzYi7RlRV5Lq04")
	if err != nil {
		return
	}

	// autogenerated func
	registreRoutes(tw)

	tw.Run()
}
